### ISSUE TITLE
Unable to paint surface

### ISSUE THREAD

**Issue by Nixola** [luapower/cairo#4]
Hi! I'm trying to use this library to make some kind of GPU-less painting program (don't ask, although the repo is public), but I am unable to paint a surface onto another one; the target surface just stays blank. The same code worked using another binding (lgi.cairo), although I had memory corruption issues with it (?) that don't seem to arise with this one.  
The issue is simple to explain: I create a source surface, a target surface and a target context, then I use ``context:source(source_surface, x, y); context:paint()`` with ``x`` and ``y`` being the coordinates I want to draw the surface at, in pixels. I checked the contents of both surfaces using ``ffi.string`` and ``save_png`` and absolutely nothing is painted to it even though the source is correct. Trying to fill some text on the target surface works. I honestly do not know what to do at this point; any suggestion, or any obvious thing I may be missing?

**Comment by capr** [comment]
Hi! My suggestion would be to isolate that code and post it here so you and I could try it. The easiest way to make a window with a cairo context which paints directly on its client area is with the nw library.

**Comment by Nixola** [comment]
Nevermind. I am an idiot and I forgot to mark the source surface as dirty after copying data inside it.
Of course, as usual, after hours of trying I only figure out what's wrong after making a fool of myself.

**Comment by capr** [comment]
Wait, how do you mark the surface as dirty? with surface:flush() ?

**Comment by Nixola** [comment]
With surface:mark_dirty(). It's quite important to do so after manually modifying the source content with ``ffi.copy(surface:data(), data)``, but I still managed to forget.

**Comment by capr** [comment]
Right, I forgot about this one too, I was trying to remember which one was it so I can fix your exmaple... so flush() before you write on the buffer and mark_dirty() after, got it.

**Comment by capr** [comment]
Btw, I noticed another post from you on libpng regarding the alpha channel, did you figure that one out?

**Comment by Nixola** [comment]
Nope! But I'll probably switch to grayscale images without alpha as brushes (or alpha masks without colour, depending on which one I can load/draw better) so it's less relevant to me now. Still, it might be useful to know though.
